name: 'ci'
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.3 

      - name: Set node version to 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Git configuration
        run: |
          git config --global user.email "amedov.bekmuhamet@gmail.com"
          git config --global user.name "phonty29"
          
      - run: pnpm install

      - name: Validate and build the package 
        run: npm run validate 

      - name: Set package version 
        run: npm version v${{ env.RELEASE_VERSION }}
        
      - name: Output package version
        run: var=$(npm view sherkhan_message version); echo $var

      - name: Publish package to NPM
        run: npm publish 
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}
